# Generated by Django 5.0 on 2024-06-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0006_admin_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_model',
        ),
    ]
