# Generated by Django 5.0 on 2024-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0007_delete_admin_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_superior', models.BooleanField(default=False)),
            ],
        ),
    ]
