# Generated by Django 5.0 on 2024-06-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0012_adminaccess_admin_model_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_model',
            name='access',
        ),
        migrations.DeleteModel(
            name='AdminAccess',
        ),
    ]
