# Generated by Django 5.0 on 2024-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0014_adminaccess_admin_model_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaccess',
            name='add_question_attempts',
        ),
        migrations.RemoveField(
            model_name='adminaccess',
            name='edit_question_attempts',
        ),
        migrations.AddField(
            model_name='adminaccess',
            name='add_question_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adminaccess',
            name='delete_question_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adminaccess',
            name='edit_question_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
