# Generated by Django 5.0 on 2024-06-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0015_remove_adminaccess_add_question_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaccess',
            name='delete_question_status',
        ),
    ]
