# Generated by Django 5.0 on 2024-06-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0016_remove_adminaccess_delete_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_model',
            name='access',
        ),
        migrations.DeleteModel(
            name='AdminAccess',
        ),
    ]
