# Generated by Django 5.0 on 2024-06-27 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0017_remove_admin_model_access_delete_adminaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz_game.admin_model')),
                ('edit_question', models.BooleanField(default=False)),
                ('add_question', models.BooleanField(default=False)),
                ('edit_question_status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('add_question_status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Admin Access Permissions',
            },
        ),
        migrations.AddField(
            model_name='admin_model',
            name='access',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_game.adminaccess'),
        ),
    ]
